# Generated by Django 6.0.2 on 2026-02-25 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Helloworld',
            new_name='HelloMessage',
        ),
    ]
